services:

  myapp:
    image: docker.io/library/myapp1 
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
    volumes:
      - .:/src
      
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - dbdata6:/data/db

volumes:
  dbdata6: